import { StyleSheet } from 'react-native';
import { SIZES, COLORS } from '../theme';

export const buttonStyles = StyleSheet.create({
  button: {
    width: '100%',
    padding: SIZES.padding / 1.5,
    backgroundColor: COLORS.primaryDark,
    alignItems: 'center',
    borderRadius: SIZES.borderRadius,
    marginVertical: SIZES.margin,
    minHeight: 48,
  },
  buttonDisabled: {
    backgroundColor: '#AAAAAA',
    opacity: 0.7,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: SIZES.fontMedium,
    fontWeight: 'bold',
  },
  floatingButton: {
    position: 'absolute',
    right: SIZES.spacingLG,
    bottom: SIZES.spacingLG,
    width: 60,
    height: 60,
    borderRadius: SIZES.borderRadiusFull,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 8,
    shadowColor: COLORS.boxshadow,
    shadowOffset: { width: 0, height: SIZES.shadowOffset },
    shadowOpacity: 0.3,
    shadowRadius: SIZES.shadowOffset,
  },
  deleteButton: {
    flex: 1,
    backgroundColor: COLORS.danger,
    padding: SIZES.spacingMD,
    marginLeft: SIZES.spacingSM,
    borderRadius: SIZES.borderRadiusSmall,
    alignItems: 'center',
    marginTop: SIZES.spacingSM,
    minHeight: 48,
  },
  cerrarButton: {
    backgroundColor: COLORS.primaryDark,
    padding: SIZES.spacingMD,
    marginLeft: SIZES.spacingSM,
    borderRadius: SIZES.borderRadiusSmall,
    alignItems: 'center',
    marginTop: SIZES.spacingSM,
    minHeight: 48,
  },
  closeButton: {
    backgroundColor: COLORS.textLight,
    padding: SIZES.spacingMD,
    borderRadius: SIZES.borderRadius,
    alignItems: 'center',
    minHeight: 48,
  },
});
