"""Agregada columna due_date a PregnancyData

Revision ID: 0e8d10fe86a7
Revises: 0d3b0203a0e8
Create Date: 2025-03-04 15:13:30.401485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8d10fe86a7'
down_revision = '0d3b0203a0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancy_data', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
