"""add google auth fields

Revision ID: 1e5259f2db6d
Revises: 996ce69cbb77
Create Date: 2025-01-30 09:11:15.907284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5259f2db6d'
down_revision = '996ce69cbb77'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'auth_provider', 
            sa.String(length=50), 
            nullable=False, 
            server_default='local'  # <--- valor por defecto
        ))
        # O si prefieres que sea nullable por ahora:
        # batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))

        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
