"""Add is_verified column to User

Revision ID: 996ce69cbb77
Revises: 39a16907fefd
Create Date: 2025-01-24 12:18:57.761971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996ce69cbb77'
down_revision = '39a16907fefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_verified',
                sa.Boolean(),
                server_default=sa.text('false'),
                nullable=False
            )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
